# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # see https://gitee.com/openharmony/docs/tree/master/docker
    container: swr.cn-south-1.myhuaweicloud.com/openharmony-docker/openharmony-docker:1.0.0
#     container: registry.us-west-1.aliyuncs.com/liux-pro/openharmony-docker:1.0.0
    env:
      HOME: /root
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # run hmp dist to build artifact
      - name: build artifact
        run:  bash -ic ". ~/.bashrc && hpm dist"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          # Artifact name
          name: Hi3861_wifiiot_app_allinone.bin
          path: ./out/BearPi-HM_Nano/Hi3861_wifiiot_app_allinone.bin
